dj_todo_pr/urls.py
from django.contrib import admin
from django.urls import path, include
from todocomp.views import Logout_func, home_View, login_view, register_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_View),
    path('register/',register_view, name= 'register_view'),
    path('login/',login_view),
    path('logout/', Logout_func),
    path('todo/', include('todocomp.urls')),
]

todocomp/urls.py
from django.urls import path
from .views import(

    delete_todo,
    add_todo_view,
    home_View,
    edit_todo_view,

)

app_name = 'todocomp'
urlpatterns = [

    path('home/', home_View , name = 'homeview'),
    path('add-todo/', add_todo_view, name = 'addtodoview'),
    path('edit-todo/<int:todo_id>/', edit_todo_view, name='edittodoview'),
    path('delete-todo/<int:todo_id>/',delete_todo, name= 'deletetodo'),

]

todocomp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# from django.contrib.sessions.models import Session
# Create your models here.


class ToDo(models.Model):
    IMPORTANCY_LEVEL_CHOICES = [
        ('Regular','regular'),
        ('Important','important')
    ]
    user = models.ForeignKey(User ,null=True,blank=True, on_delete=models.CASCADE,related_name='todos')
    todo_title = models.CharField(max_length=200, null=True ,blank=True)
    todo_text = models.CharField(max_length=200, null=True, blank=True)
    expire_date = models.DateField(null=True, blank=True)
    importancy_level = models.CharField(max_length=20,choices=IMPORTANCY_LEVEL_CHOICES,default= 'Regular')
    is_accomplished = models.BooleanField(null = True , blank = True , default=False)

todocomp/forms.py
from django import forms
from .models import ToDo


class TodoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields =('todo_title','todo_text', 'expire_date','importancy_level','is_accomplished')

        widget = {
            'todo_title' : forms.TextInput(attrs= {'class' : 'form-control'} ),
            'todo_text' : forms.TextInput(attrs=  {'class' : 'form-control '}),
            'expire_date' : forms.DateInput(attrs=  {'class' : 'form-control '} ),
            'importancy_level' : forms.Select(attrs=  {'class' : 'form-control '} ),
            'is_accomplished' : forms.Select(attrs= {'class' : 'form-control '} ),

        }



class RegisterForm(forms.Form):
    username = forms.CharField(max_length= 100)
    email = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50)




class LoginForm(forms.Form):
    username = forms.CharField(max_length= 100)
    password = forms.CharField(max_length=50)

todocomp/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render,redirect
from django.http import (
    HttpResponse,
    
)

from .forms import TodoForm, RegisterForm, LoginForm
from .models import ToDo
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
# Create your views here.



def home_View(request,*args,**kwargs):
    if not request.user.is_authenticated:
        return redirect("/login/")
        
    try:
        obj = request.user.todos.all()

    except:
        context = { "object" : None}
        return render(request,'main.html', context )
    context = { "object" : obj}
    
    return render(request,'main.html', context )


def register_view(request, *args, **kwargs):
    context = {'form' : RegisterForm}
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user_object = User.objects.create(username = username, email = email , password= password)
            user_object.save()
       
            if user_object is not None:
                login(request, user_object)
                return redirect('/todo/home')
            else:
                print("is None")
    return render(request, 'register.html', context)

def login_view(request, *args, **kwargs):
    context = {'form' : LoginForm}
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/todo/home')



    return render(request, 'login.html', context)

def Logout_func(request, *args, **kwargs):
    logout(request)

    return redirect('/todo/home')





@login_required(login_url='/login/')
def add_todo_view(request,*args,**kwargs):
    context ={ 'form' : TodoForm}
    if request.method == "GET":
        return render(request, "add_todo.html", context )

    form = TodoForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)

        obj.user = request.user
    
        obj.save()

        return redirect("/todo/home/")


    return render(request, "add_todo.html", context )


@login_required(login_url='/login/')
def edit_todo_view(request,todo_id, *args,**kwargs):
    instance_get = request.user.todos.get(id = todo_id)
    form_object = TodoForm(instance= instance_get)
    context = {'form' : form_object }
    if request.method == "GET":
        return render(request, 'add_todo.html',context)

    form_object = TodoForm(request.POST, instance= instance_get)
    if form_object.is_valid():
        obj = form_object.save()
        return redirect('/todo/home/')
    



    return render(request, 'add_todo.html', context)

@login_required(login_url='/login/')
def delete_todo(request,todo_id,*args,**kwargs):
    obj = request.user.todos.get(id = todo_id).delete()

    return redirect('/todo/home/')

templates/add_todo.html
{% extends 'base.html '%}

{% block content %}


 
  <div class="container bg-warning col-md-12 ">

    <div class="py-5 text-center">

      <h2>Create A To-Do</h2>

    </div>
    <div class="text-center col-md-12 order-md-3 form-group"> 
      <form method="POST" action="" class="cold-md-12">
      <!-- {{ form.error }} -->
      {% csrf_token %}   
      {{ form.as_p }}
      <button type="submit" class="btn btn-danger col-md-8 mr-auto btn-lg">Add To Do</button>

    </form>
    </div>
    





  </div>






{% endblock %}

templates/base.html
<!Doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">



  <title>To Do List</title>
  {% block style_block %}     {% endblock style_block %}
  
</head>

<body>


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a href='{% url 'todocomp:homeview' %}' class="navbar-brand"> To Do List</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>

    </button>>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto ">
        <li class="nav-item active">
          <a class="nav-link" href='{% url 'todocomp:homeview' %}' >Home <span class="sr-only"></span></a>
        </li>

        <li class="nav-item active ">
          <a class="nav-link" href='{% url 'todocomp:addtodoview' %}'>Add To-Do <span class="sr-only">(current)</span></a>
        </li>


        <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div> -->
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#" tabindex="-1" aria-disabled="true">My Progress</a>
        </li>
      </ul>

      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
    </div>


  </nav>

  <br>
  {% block content %}


  sdf



  {% endblock content %}

  <br>

  <!-- Footer -->
  <footer class="bg-light text-center text-lg-start">

    <div class="container p-4">

      <div class="row">

        <div class="col-lg-12 col-md-12 mb-4 mb-md-0">
          <h5 class="text-uppercase">In production</h5>

          <p>
            In production
          </p>
        </div>




      </div>

    </div>



    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      To-Do List Web Application

    </div>

  </footer>








  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
    crossorigin="anonymous"></script>

</body>

</html>

templates/login.html
{% extends 'base.html' %}

{% block style_block %}


{% endblock style_block %}

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>


{% block content %}
<div class="container bg-warning col-md-5 " style="margin: auto;  text-align: center;">
    <div class="py-5 text-center">



        <div>
            <h2 class="h2 mb-3 font-weight-normal">Please Log In</h2>
        </div>


        <div class="text-center col-md-12 order-md-3 form-group"> 
            <form method="POST" action="" class="cold-md-12">

            {% csrf_token %}   
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger col-md-8 mr-auto btn-lg">Log In</button>
      
          </form>
            <br>
            <a href='{% url 'register_view' %}'
                <button   class="btn btn-primary col-md-8 mr-auto btn-lg"> Go Register</button>
            </a>

          </div>
    </div>
</div>




{% endblock content %}

templates/main.html
{% extends 'base.html' %}



{% block content %}


<div class="container">
  <div class="row">
    {% if object %}
    {% for todos in object %}

    <div class="card col-lg-4 col-md-6 mb-4 " style="width: 18rem;">

      <div class="card-body">
        <h5 class="card-title">{{ todos.todo_title  }}</h5>
        {% if todos.todo_text %}
        <p class="card-text">{{ todos.todo_text  }}</p>
        {% else %}
        <p class="card-text"> Does not have text</p>
        {% endif %}

        {% if todos.expire_date %}
        <p class="card-text">{{ todos.expire_date  }}}</p>
        {% else %}
        <p class="card-text"> Does'nt have expire date</p>
        {% endif %}
        <a href="{% url "todocomp:edittodoview" todos.id %}" class="btn btn-warning">Edit</a>
        <a href="{% url "todocomp:deletetodo" todos.id %}" class="btn btn-primary">Done</a>
 
      </div>
    </div>

    {% endfor %}
    {% else %}
<a href='{% url 'todocomp:addtodoview' %}'> 
  <h1 class="text-center"> You Do Not Have Any Todos Click Here To Create One </h1> </a>
    {% endif %}



    <!-- 
      <div class="card-body">
        <h5 class="card-title">Title</h5>
        <p class="card-text">Do this later</p>
        <a href="#" class="btn btn-primary">Edit</a>
      </div>
    </div>
    <div class="card col-lg-4 col-md-4 mb-4 shadow-sm" style="width: 18rem;">

 -->
  </div>




</div>



{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block style_block %}


{% endblock style_block %}

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>


{% block content %}
<div class="container bg-warning col-md-5 " style="margin: auto;  text-align: center;">
    <div class="py-5 text-center">



        <div>
            <h2 class="h2 mb-3 font-weight-normal">Please Sign In</h2>
        </div>


        <div class="text-center col-md-12 order-md-3 form-group"> 
            <form method="POST" action="" class="cold-md-12">

            {% csrf_token %}   
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger col-md-8 mr-auto btn-lg">Add To Do</button>
      
          </form>
          </div>
    </div>
</div>




{% endblock content %}